# Generated by Django 5.1.4 on 2026-04-22 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('overwrite', 'Overwrite'), ('delete', 'Delete'), ('download', 'Download'), ('preview', 'Preview')], max_length=32)),
                ('file_id', models.UUIDField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files_audit_log',
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'), models.Index(fields=['action'], name='audit_action_idx')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=127)),
                ('extension', models.CharField(max_length=10)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleting', 'Deleting')], default='uploading', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files_file',
                'indexes': [models.Index(fields=['owner', '-created_at'], name='files_owner_created_idx'), models.Index(fields=['owner', 'name'], name='files_owner_name_idx'), models.Index(fields=['status'], name='files_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ready')), fields=('owner', 'name'), name='unique_ready_file_per_owner_name')],
            },
        ),
    ]
